### ISSUE TITLE
Release to crates.io

### ISSUE THREAD

**Issue by MathiasKoch** [BlackbirdHQ/mqttrust#11]
Currently a few things are blocking a release to crates.io

- [x] https://github.com/BlackbirdHQ/ublox-cellular-rs/issues/17 / https://github.com/BlackbirdHQ/ublox-cellular-rs/issues/19
- [x] Release of defmt (https://github.com/knurling-rs/defmt/)
- [x] https://github.com/00imvj00/mqttrs/pull/29
- [ ] Better documentation
- [ ] #2

**Comment by keisrk** [comment]
Yesterday `00imvj00/mqttrs` merged your PR. Congrats!

**Comment by MathiasKoch** [comment]
https://crates.io/crates/mqttrust

https://crates.io/crates/mqttrust_core
