### ISSUE TITLE
Split trait from implementation

### ISSUE THREAD

**Issue by MathiasKoch** [BlackbirdHQ/mqttrust#26]
I would like to see this crate split into a workspace of two crates:
- The mqtt abstraction (the trait)
- The actual implementation

This would allow us to do changes to the implementation, without higher level crates like [`rustot`](https://github.com/BlackbirdHQ/rustot/) having to bump it's dependency version, unless the actual trait signature has changed.

This would furthermore allow people to easier use higher level mqtt crates with other mqtt clients, as long as they implement the shared abstraction.

**Any suggestions on naming of said abstraction crate?**

**Comment by keisrk** [comment]
How about calling the trait simply `mqttrust::Client`, the same way as these projects?
[rumqtt](https://github.com/bytebeamio/rumqtt/blob/master/rumqttc/src/client.rs#L29)
[modbus](https://github.com/slowtec/tokio-modbus/blob/master/src/client/mod.rs#L21)
[redis](https://github.com/tokio-rs/mini-redis/blob/master/src/client.rs#L23)
And in a separated workspace, say `mqttrust_core`, we can name `mqttrust_core::Client` for the actual implementation?
